amovieplex/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("frontend.urls")),
    path("admin/dashboard/", include("dashboard.urls")),
]

if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls))
    ] + urlpatterns

dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Auth
    path("login", views.LoginView.as_view(), name="dashboard.login"),
    path("logout", views.LogoutView.as_view(), name="dashboard.logout"),
    # Dashboard
    path("", views.DashboardView.as_view(), name="dashboard.index"),
    # Movies
    path("movies/", views.MovieListView.as_view(), name="dashboard.movie.list"),
    path(
        "movies/<int:pk>",
        views.MovieDetailView.as_view(),
        name="dashboard.movie.detail",
    ),
    path(
        "movies/create",
        views.MovieCreateView.as_view(),
        name="dashboard.movie.create",
    ),
    path(
        "movies/<int:pk>/edit",
        views.MovieUpdateView.as_view(),
        name="dashboard.movie.edit",
    ),
    # Movie Medias
    path(
        "movie-medias",
        views.MovieMediaView.as_view(),
        name="dashboard.movie_medias",
    ),
    path(
        "movie-medias/<int:movie_id>",
        views.medias_of_movie,
        name="dashboard.medias"
    ),
    # Show Times
    path(
        "showtimes",
        views.ShowTimeListView.as_view(),
        name="dashboard.show_times"
    ),
    path(
        "showtimes/<int:movie_id>",
        views.ShowTimeDetailView.as_view(),
        name="dashboard.show_times.details"
    ),
    path(
        "showtimes/<int:pk>/edit",
        views.ShowTimeUpdateView.as_view(),
        name="dashboard.show_times.edit"
    ),
    path(
        "screentimes/create",
        views.ScreenTimeCreateView.as_view(),
        name="dashboard.screen_times.create"
    ),
    path(
        "formclose",
        views.HeadLessFormCloseView.as_view(),
        name="dashboard.formclose"
    )
]

frontend/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("movie/<int:pk>", views.SingleMovie.as_view(), name="single_movie"),
    path("user/dashboard", views.UserDashboardView.as_view(), name="user_dashboard"),
    path("user/tickets", views.UserTicketView.as_view(), name="user_tickets"),
    path("user/reviews", views.UserReviewView.as_view(), name="user_reviews"),
    path("user/edit-profile", views.UserEditProfileView.as_view(), name="profile_edit"),
    path("user/change-password", views.UserChangePasswordView.as_view(), name="change_password"),
    path("user/signup", views.UserRegistrationView.as_view(), name="user_signup"),
    path("user/login", views.UserLoginView.as_view(), name="user_login"),
    path("user/logout", views.UserLogoutView.as_view(), name="user_logout")
]

dashboard/models.py
from django.db import models

# Create your models here.

movie/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.core.validators import MinValueValidator, MaxValueValidator
from django.apps import apps
from django.urls import reverse


class Genre(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title


class Rating(models.Model):
    title = models.CharField(max_length=10)
    age_limit = models.SmallIntegerField()

    def __str__(self):
        return self.title


class Movie(models.Model):
    title = models.CharField(max_length=200)
    short_plot = models.CharField(max_length=300)
    plot = models.TextField()
    director = models.CharField(max_length=200)
    starring = models.CharField(max_length=200)
    release_date = models.DateField(blank=True, null=True)
    running_time = models.IntegerField(blank=True, null=True)
    genres = models.ManyToManyField(Genre, related_name='genres')
    rating = models.ForeignKey(Rating, null=True, on_delete=models.SET_NULL)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_genres(self):
        movie_genres = self.genres.all()
        genres = movie_genres[0].title
        for genre in movie_genres[1:]:
            genres = genres + ', ' + genre.title
        return genres

    def get_feature_image(self):
        media_type = MediaType.objects.filter(type='Feature').first()
        feature_image = MovieMedia.objects.filter(
            movie=self, media_type=media_type).first()
        return feature_image

    def get_poster_image(self):
        media_type = MediaType.objects.filter(type='Poster').first()
        poster = MovieMedia.objects.filter(
            movie=self, media_type=media_type).first()
        return poster

    def get_general_images(self):
        media_type = MediaType.objects.filter(type='General').first()
        images = MovieMedia.objects.filter(
            movie=self, media_type=media_type)
        return images

    def get_all_images(self):
        media_type = MediaType.objects.filter(type='Video').first()
        images = MovieMedia.objects.filter(
            movie=self).exclude(media_type=media_type)
        return images

    def get_all_videos(self):
        media_type = MediaType.objects.filter(type='Video').first()
        videos = MovieMedia.objects.filter(
            movie=self, media_type=media_type)
        return videos

    def get_show_times(self):
        ShowTime = apps.get_model('theater', 'ShowTime')
        show_times = ShowTime.objects.filter(movie=self)
        return show_times

    def get_comments(self):
        comments = Comment.objects.filter(movie=self)
        return comments

    def get_slug(self):
        return slugify(self.title)


class MediaType(models.Model):
    type = models.CharField(max_length=20)

    def __str__(self):
        return self.type


class MovieMedia(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="movie_images/", blank=True, null=True)
    video_url = models.CharField(max_length=100, blank=True, null=True)
    media_type = models.ForeignKey(
        MediaType, null=True, on_delete=models.SET_NULL)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.image.url


class Comment(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=300)
    rate = models.PositiveSmallIntegerField(
        default=5, validators=[MinValueValidator(1), MaxValueValidator(5)])
    commented_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('movie', 'user')

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse("single_movie", kwargs={"pk": self.movie.id})

dashboard/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column

from movie import models as movie_models
from theater import models as theater_models
from django.utils.safestring import mark_safe


class MovieForm(forms.ModelForm):
    class Meta:
        model = movie_models.Movie
        fields = (
            "title",
            "short_plot",
            "plot",
            "director",
            "starring",
            "release_date",
            "running_time",
            "genres",
            "rating",
        )


class MovieMediaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["movie"].widget = forms.HiddenInput()

    class Meta:
        model = movie_models.MovieMedia
        fields = ("movie", "media_type", "image", "video_url")


class ShowTimeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["movie"].widget = forms.HiddenInput()

    class Meta:
        model = theater_models.ShowTime
        fields = ("movie", "hall", "screen_day", "screen_times")


class ScreenTimeForm(forms.ModelForm):
    class Meta:
        model = theater_models.ScreenTime
        fields = ("movie", "start_time", "end_time")

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect
from movie import models as movie_models
from theater import models as theater_models
from . import forms
from django.http import HttpResponse
from django.core import serializers


class LoginView(LoginView):
    template_name = "dashboard/auth/login.html"
    redirect_authenticated_user = True
    extra_context = {"page_title": "Admin Login"}

    def get_success_url(self):
        url = self.get_redirect_url()
        return url or reverse("dashboard.index")


class LogoutView(LogoutView):
    next_page = "/admin/dashboard/login"


class DashboardView(LoginRequiredMixin, TemplateView):
    login_url = "/admin/dashboard/login"
    extra_context = {"page_title": "Dashboard"}
    template_name = "dashboard/index.html"


class MovieListView(LoginRequiredMixin, ListView):
    login_url = "/admin/dashboard/login"
    extra_context = {"page_title": "Movies"}
    template_name = "dashboard/movies/movie_list.html"
    model = movie_models.Movie
    context_object_name = "movies"
    ordering = ["-release_date"]


class MovieDetailView(LoginRequiredMixin, FormMixin, DetailView):
    model = movie_models.Movie
    template_name = "dashboard/movies/movie_detail.html"
    extra_context = {"page_title": "Movie Detail"}
    form_class = forms.MovieMediaForm

    def get_success_url(self):
        return reverse("dashboard.movie.detail", kwargs={"pk": self.object.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        media_form = self.get_form()
        media_form.fields["movie"].initial = self.object.pk
        context["form"] = media_form
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            # Has some bug form resubmission occur in reload on invalid form
            return self.form_invalid(form)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.save()
        return redirect(self.get_success_url())


class MovieCreateView(LoginRequiredMixin, CreateView):
    login_url = "/admin/dashboard/login"
    extra_context = {"page_title": "New Movie"}
    model = movie_models.Movie
    form_class = forms.MovieForm
    template_name = "dashboard/movies/movie_form.html"


class MovieUpdateView(LoginRequiredMixin, UpdateView):
    login_url = "/admin/dashboard/login"
    extra_context = {"page_title": "Update Movie"}
    model = movie_models.Movie
    form_class = forms.MovieForm
    template_name = "dashboard/movies/movie_form.html"
    success_url = reverse_lazy("dashboard.movie.list")


class MovieMediaView(LoginRequiredMixin, FormMixin, TemplateView):
    login_url = "/admin/dashboard/login"
    extra_context = {"page_title": "Movie Medias"}
    template_name = "dashboard/movie_medias/index.html"
    form_class = forms.MovieMediaForm

    def get_success_url(self):
        return reverse("dashboard.medias")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        all_movies = movie_models.Movie.objects.all()
        context["movies"] = all_movies
        media_form = self.get_form()
        media_form.fields["movie"].initial = all_movies[0].id
        context["form"] = media_form
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            # Has some bug form resubmission occur in reload on invalid form
            return self.form_invalid(form)

    def form_valid(self, form):
        movie_media = form.save(commit=False)
        movie_media.save()
        return redirect(self.get_success_url())


def medias_of_movie(request, movie_id):
    movie_medias = movie_models.MovieMedia.objects.filter(movie=movie_id)
    data = serializers.serialize("json", movie_medias)
    return HttpResponse(data, content_type="application/json")


class ShowTimeListView(LoginRequiredMixin, ListView):
    login_url = "/admin/dashboard/login"
    extra_context = {"page_title": "Show Times"}
    template_name = "dashboard/show_times/show_times_list.html"
    model = movie_models.Movie
    context_object_name = "movies"
    ordering = ["-release_date"]


class ShowTimeUpdateView(LoginRequiredMixin, UpdateView):
    login_url = "/admin/dashboard/login"
    extra_context = {"page_title": "Update Screen Time"}
    model = theater_models.ShowTime
    form_class = forms.ShowTimeForm
    template_name = "dashboard/headless_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        show_time_form = self.get_form()
        show_time_form.fields[
            "screen_times"
        ].queryset = theater_models.ScreenTime.objects.filter(
            movie=self.object.movie
        )
        context["form"] = show_time_form
        return context

    def get_success_url(self):
        return reverse_lazy("dashboard.formclose")


class ShowTimeDetailView(LoginRequiredMixin, FormMixin, DetailView):
    model = movie_models.Movie
    template_name = "dashboard/show_times/show_times_detail.html"
    extra_context = {"page_title": "Movie Show Time"}
    form_class = forms.ShowTimeForm
    slug_field = "pk"
    slug_url_kwarg = "movie_id"

    def get_success_url(self):
        return reverse(
            "dashboard.show_times.details", kwargs={"movie_id": self.object.pk}
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        media_form = self.get_form()
        media_form.fields["movie"].initial = self.object.pk
        # Only showing the screen times associated with the movie
        media_form.fields[
            "screen_times"
        ].queryset = theater_models.ScreenTime.objects.filter(movie=self.object)
        context["form"] = media_form
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            # Has some bug form resubmission occur in reload on invalid form
            return self.form_invalid(form)

    def form_valid(self, form):
        show_time = form.save(commit=False)
        show_time.save()
        return redirect(self.get_success_url())


class ScreenTimeCreateView(LoginRequiredMixin, CreateView):
    login_url = "/admin/dashboard/login"
    extra_context = {"page_title": "New Screen Time"}
    model = theater_models.ScreenTime
    form_class = forms.ScreenTimeForm
    template_name = "dashboard/show_times/headless_form.html"


class HeadLessFormCloseView(LoginRequiredMixin, TemplateView):
    login_url = "/admin/dashboard/login"
    extra_context = {"page_title": "Movie Medias"}
    template_name = "dashboard/headless_form_close.html"

dashboard/templates/dashboard/movie_medias/index.html
{% extends 'dashboard/base.html' %}
{% load crispy_forms_tags %}

{% block css %}

<link type="text/css" rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.6.12/css/lightgallery.min.css" />

{% endblock css %}

{% block content %}

<div class="row">
    <div class="col-3">
        <h5>Movies</h5>
        <div class="list-group" style="overflow-y: scroll; max-height: 400px;">
            {% for movie in movies %}
            <button type="button" class="list-group-item list-group-item-action {% if forloop.first %}active{% endif %}"
                data-movie_id={{movie.id}} onclick="getMovieMedias(this)">
                {{ movie.title }}
            </button>
            {% endfor %}
        </div>

    </div>
    <div class="col">
        <div class="card shadow mb-4">
            <!-- Card Header - Accordion -->
            <a href="#collapseNewMovieMedia" class="d-block card-header py-3" data-toggle="collapse" role="button"
                aria-expanded="true" aria-controls="collapseNewMovieMedia">
                <h6 class="m-0 font-weight-bold text-primary">New Movie Media</h6>
            </a>
            <!-- Card Content - Collapse -->
            <div class="collapse" id="collapseNewMovieMedia">
                <div class="card-body">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary btn-user btn-block">
                            New Media
                        </button>
                    </form>
                </div>
            </div>
        </div>
        <div class="card shadow mb-4">
            <!-- Card Header -->
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Movie Medias</h6>
            </div>
            <!-- Card Content-->
            <div class="card-body" style="overflow-y: scroll; max-height: 600px;">
                <div id="aniimated-thumbnials">
                    {% with movies|first as first_movie %}
                    {% for image in first_movie.get_all_images %}
                    <a href="{{image}}">
                        <img class="img-thumbnail m-1" style="height: 100px; width:150px; object-fit: contain;"
                            src={{ image }} />
                    </a>
                    {% endfor %}

                    {% for video in first_movie.get_all_videos %}
                    <a href="https://www.youtube.com/watch?v={{video.video_url}}">
                        <img class="img-thumbnail m-1" style="height: 100px; width:150px; object-fit: contain;"
                            src="//img.youtube.com/vi/{{video.video_url}}/default.jpg" />
                    </a>
                    {% endfor %}
                    {% endwith %}
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}


{% block js %}
<!-- A jQuery plugin that adds cross-browser mouse wheel support. (Optional) -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-mousewheel/3.1.13/jquery.mousewheel.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.6.12/js/lightgallery-all.min.js"></script>

<script>
    let animatedThumbnail = $('#aniimated-thumbnials');
    animatedThumbnail.lightGallery({
        thumbnail: true,
        animateThumb: false,
        showThumbByDefault: true,
        loadYoutubeThumbnail: true,
        youtubeThumbSize: 'default',
    }); 
</script>
<script>
    let currentMovie = 1;
    let rootUrl = window.location.origin;
    function getMovieMedias(movie) {
        let allListItem = document.getElementsByClassName('list-group-item');
        Array.from(allListItem).forEach(listItem => {
            if (listItem.className.includes('active'))
                listItem.className = listItem.className.replace(' active', '');
        });
        movie.className += ' active'

        let movieId = movie.getAttribute('data-movie_id')

        $('#id_movie').val(movieId)

        if (currentMovie !== movieId) {
            currentMovie = movieId
            let mediaUrl = `/admin/dashboard/movie-medias/${currentMovie}`
            $.ajax({
                url: mediaUrl,
                type: "GET",
                success: function (data) {
                    animatedThumbnail.empty();
                    let content = '';
                    data.forEach(element => {
                        let media = element.fields
                        if (media.video_url === null) {
                            content += `<a href="${rootUrl}/media/${media.image}">
                                <img class="img-thumbnail m-1" style="height: 100px; width:150px; object-fit: contain;" src="${rootUrl}/media/${media.image}" />
                            </a>`
                        } else {
                            content += `<a href="https://www.youtube.com/watch?v=${media.video_url}">
                                <img class="img-thumbnail m-1" style="height: 100px; width:150px; object-fit: contain;"
                                    src="//img.youtube.com/vi/${media.video_url}/default.jpg" />
                            </a>`
                        }
                    });
                    animatedThumbnail.append(content);
                    animatedThumbnail.data('lightGallery').destroy(true);
                    animatedThumbnail.lightGallery();
                },
                error: function (error) {
                    console.log(error);
                }
            })
        }
    }
</script>
{% endblock js %}